b2_account_id: ENC[AES256_GCM,data:j3SmRtx6bsf3YOvRYCqWTEjSVcH78IKkVg==,iv:4qbjsQ7Nub6Ms7MsM5AuCJn0e2FwNX1vWhO+ZiVhhfU=,tag:NFT8LZYvMB+ZXNUICeowvQ==,type:str]
b2_account_key: ENC[AES256_GCM,data:MeaWv/o4jdmWnK1CQBPVxj/XyioQGrUzLsj82E1NwA==,iv:sJLT4OFyeR6tNiiPGLfXvqn0Ds8EwujtGerrqKcbm9U=,tag:AfzJ5aXpcZyRocc+c4D1Yg==,type:str]
restic_password: ENC[AES256_GCM,data:l9XWqPy3FhbOBqD0A1nzCbdS8Uufc+p2hrVeM6QZBDxiXqmO8QUN5fBJgEjdxZSKYlc=,iv:zojvxnc4Hort+7YXYSKnFl1upMltbsK8mZrK0yxEauc=,tag:SiY+O+mAXWTSU5ikDLxTMQ==,type:str]
restic_repo_base: ENC[AES256_GCM,data:HzuOAC3e6BxDEQhKxU+RmfM+5sfxwA8=,iv:EoFGRGe4iiqkwfgcR8c0ExPzKzuJwMKafgTYJh1uaOQ=,tag:oXObc0acbfLGW2QiSlI+qA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUU9TalIxNG1ROXhJb2No
            bHl3WVFFRGM5MFdCM25GcXFRMWxEZkhWc2dzCkJQaHROTEZOQmpocG04MUhycGR2
            M0ZOVjRRWFQwSjZ3RUlRR01KTVJrRncKLS0tIFJ3OG55dkRxSXhkT3pnV2VUM2tn
            bmlyaDJaWHBOTDFjeW1hMTU4NVJqK3cKkyRA8cKJoXE20bJBR9DGlyHpkSwt+sY0
            bvS2Val5iL9+qTjx83ifAMKk8qL5jtARtCxo4419ppHl7wh0xXKNYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vdye4f7xpwan2nl7a3ne7nxyt0xx96ksvvy8gtlluxjpmpz7fp0spf2j6d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldkxmNjhuOUNPWnBSVzhl
            ZVZ6aGlIQVVRNjZvNFdMK0EyRlRNM0lEK1d3ClhCRVY5Um1qK3puUGp2NmVLbVBW
            QzU1dWo3bm5rR3UzVjlTaGN5VXpiaWMKLS0tIDIzdjNWRmI1WjRwSXZSTHYwelNQ
            NHRibWM4WUtESkZEMUswemJrNjNqUTgKo8mtg4s462SqVsSQDT/M8ynq4Faj46ZA
            aKjJvfXTQqbSiZLYdTtPE4FwBZii1a55+tEKQGieuOGDr2c5Rq1maw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10cwjzcr4x42qnumwlwh4k7kdvunaef9a6qdhpqrmaq2nz8mr0qss8t4syd
    lastmodified: "2026-07-04T21:20:16Z"
    mac: ENC[AES256_GCM,data:GnPqX65f5ANPUTxZnC3pyrWBlTE0e3ZiSBjQfxx8qiBhlHk+ULqY/KtfZTuNVs1LTz7CWZeTJeZQwLSbRQiBIwlU/MKSs4j14Qx2UVfsvz8oNHnkMoX+2UJfSdwPd4UU85/GrlzK6l/ljQZcBXOnL3KqmD+bgcocutJA8el/BrA=,iv:ew1LWch6bIy7gQ9Rvd/1oyzhtFp1YeZB0OtnSZ6rp/U=,tag:rwGThWRrotNIv5X0Crveug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
