tailscale_authkey: ENC[AES256_GCM,data:n6KVOdHxswz7v3B+MBfbaHjRVi7UMvQPW5o6NWKyNTy6uJDorMV34WpOGSofQH5GAB4RGKi0aYelnaPlqA==,iv:SNi5+GPUC1dgZ7t6blAjv+O9rsvTeKDy0v5DrJtzATM=,tag:UwaSR1TV68thxgfSEnoEWQ==,type:str]
authentik_secret_key: ENC[AES256_GCM,data:NcNhZbvnmPTLt5Re8m1uqUuo8zRIPj5KvBF5SFJ4wYRel2KLZNsuLH7HzgT/Ujy6GpxnsKWE9QZ9LVSChM8DcL1nUpE=,iv:VhOW8J7dYcVSLsjHj88FaYhGLFY69BHbFPM2YjAl4vs=,tag:My7H3XoKCCJwSHosgavCrA==,type:str]
authentik_db_password: ENC[AES256_GCM,data:EWjrKWJF2CX4IS6IE/fhyTC66lsiXSu+LT7WmM5yPOjfvcl350aSsiySTV+fmeIw,iv:klgINfMB4IPBTNO310f94RBo8XZaEX9M3PuBa3jSShM=,tag:PQOyN4h1lFi8ANtWD1bI4g==,type:str]
grafana_password: ENC[AES256_GCM,data:ms9nf/Qkh2uZg/zef7Md+oVKnzjcRl4biB2sgjHFnnU6MbHD0p3fQhq60WLauem2hFM=,iv:C5CE6TsLrISICOEHnLCDo7QT8F6vMlyakCSc6iGPFTM=,tag:HWK4Ypu6qeuZjBBtdZFvGA==,type:str]
healthchecks_uuid: ENC[AES256_GCM,data:6UnuYY46FND20hga/+QHIx3svAEV/21zE1gjMbjaDyEU9QK8,iv:Dz1mdda90rS6z5LEwXE9aIUr8fpsfy2xD5wxBjgq7MY=,tag:wBO56YQBx3egZEHUb8q1Ug==,type:str]
pve_password: ENC[AES256_GCM,data:RPU476oS3StcimB+p02IBjEd6w5y4mhB2aoj4mfDVhr+a1L8Ozq7YlsKmeA1qvVuVvY=,iv:lxGy/sgfNhJrGZfNfhpqVBQr9MANndWEOnAPdJ1Uewc=,tag:w7UVRRmrkFwfsDjg78w3vg==,type:str]
ntfy_token: ENC[AES256_GCM,data:i6d9HKn2nLia+LVPMrBedJXu7qR1pxrL3cctdt9aTHQ=,iv:vdQERL/wylncWMmGhb2Vy8MDJeSYV6twLr5LHokKNNk=,tag:A0FYN13lobjj/0hZovqTEg==,type:str]
vaultwarden_admin_token: ENC[AES256_GCM,data:Vg+OcYH9UEvK4yMQIBsulhxKS0m0C4Xhhrb1zzXBG7mtPFiNmvOSil20jRSrhx2r/Ro=,iv:urUNZJcjTKuaUXC/u8xfl5UN22NX9u7vgvUUxH4aGEI=,tag:CtDNC+MyCPzxPmmVf3pZPQ==,type:str]
speedtest_app_key: ENC[AES256_GCM,data:J5D1XPju4rGHwqQz3BGd87KdkkpOihBlWyIcrtaH0tYvWp7T+7ZODz11GupnQN3z4Uz9,iv:fr+42iZWc8He1NKKr78dI68OnuM9eAewKGKZOW8OM8U=,tag:Pt0fGwZMYAkAc2h7AcWJRA==,type:str]
miniflux_db_password: ENC[AES256_GCM,data:jAhbkVtao7GAbwq2y8HlK+CEoBJ7IcZ5XHFnla040nC5U8xfyXjIYWNYMbrCD3ZTmQM=,iv:fPORvMdJ/L3c2vwgHvHS2BYqsoENPhV0J+9q4bYHl+g=,tag:Z+YJGjGQW5Z3+EIj9uLrMQ==,type:str]
miniflux_admin_password: ENC[AES256_GCM,data:wuG5cRrkhldHLJHBPKnGKrSMdkT9NSJK9Xnes1crno9gzf/PtOTVgNxt79/wrmWOXIE=,iv:9Q+Tj1DDLDuhN/o2w7n56cm7Eve/I+Llxny4xgrrSIw=,tag:tjeMZKs2FdyIjJrD66uHLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUVpjcE1RMHRHN2VNTEll
            RXhtVHYrbmJPUEFmaGJWdTZVSWxIK0paUXpFCmlIYVFoVVdZZmRFdkRucnBUaC9U
            QUNnZFhnSDE1ZmFsSkJzQVJocW5qVjgKLS0tIDBsZysvZUwweVYvWU5WcTIwUnVM
            VGRoR3oyZjZNMnJDVFF0Q1lrUnFXbEUKb0GNF8/dJE6JgUvxO3lVUtsjtu4r6A8d
            DqM1v2oqzWONeKUzO4XuWiqwCXJuYB4njeMDmMx3dl5forMGNlh0Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vdye4f7xpwan2nl7a3ne7nxyt0xx96ksvvy8gtlluxjpmpz7fp0spf2j6d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSVRoM0t1Q2g1bkNPWUdO
            Q3lDVis1US9lbUE0VTBaRlNlRW5iVHRMcWhBClBmcHlxQUVCYkdWMm9icDVYOUZP
            TFh2UXErN2liSmRwU2ZISTdVK01KVUUKLS0tIGRsSGI5TzdEWFNpalgyV3lPY3pm
            MDc4aEZocWd2eThCQTB5TlVDTXVUazQKuS3KLipX28g5cSaKHL6ie9n8xhV1m21m
            U1ehjJzz9ZsHGilDIyOCHojQ+rrrsJoW2N2BJgBcxCW76CH9iQU9SQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10cwjzcr4x42qnumwlwh4k7kdvunaef9a6qdhpqrmaq2nz8mr0qss8t4syd
    lastmodified: "2026-07-04T21:03:03Z"
    mac: ENC[AES256_GCM,data:5QbvBVEF7tN0Jw+xdisMh9DWAMjFY4zYN6cBdw7oA5AnMFuSQYRm/dlgXZjMPPBQskjIRI8GWsMnn5ZCFxzzwQR4nogJ7Ox8e8nw1a19djz1u2gLSEOltfscNlHwBjdEaQBsWkRKQSw1SHB1s8DCI3Lxq4IXloBmOVDPyYmj/k0=,iv:dOcrSxeBVYOgJQUztWrX1APMP0dj+MVmdY+jj7e/yWQ=,tag:vk4dNG2sVicmk6bNQLxHYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
