base_dir: "/opt/services"
auth_dir: "/opt/auth"
mon_dir: "/opt/monitoring"
sec_dir: "/opt/security"
alertmanager_dir: "{{ mon_dir }}/alertmanager"
pve_dir: "{{ mon_dir }}/pve"

freshrss_extensions:
  - name: "xExtension-AiSummary"
    repo: "https://github.com/deimosfr/xExtension-AiSummary.git"
    version: "6f576f3a9ecbf9f6679d120524bb31d5614f1c4c"
  - name: "xExtension-DateFormat"
    repo: "https://github.com/aledeg/xExtension-DateFormat.git"
    version: "594647768a83516d0c8ba05bc3616dcb5def08ea"
  - name: "xExtension-YouTubeDuration"
    repo: "https://github.com/cevvalkoala/xExtension-YouTubeDuration.git"
    version: "57b95bbd27bbf98e49af9b235de869ceda705938"
  - name: "xExtension-YouTube"
    repo: "https://github.com/FreshRSS/Extensions.git"
    version: "5c3250d57d4e0bde0504997fd85ee1dd98d34ac8"
    subdir: "xExtension-YouTube"
