[intelbras]
    driver = usbhid-ups
    port = auto
    desc = "Intelbras Gamer Ultimate"
    vendorid = 0764
    productid = 0601
    ignorelb
    override.battery.charge.low = 50
    override.input.voltage.nominal = 220
