MONITOR intelbras@localhost 1 upsmon_local rpi_senha_interna primary
MINSUPPLIES 1
SHUTDOWNCMD "/usr/local/bin/ups-kill.sh"
POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 30
POWERDOWNFLAG /etc/killpower
