apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # URL interna da rede do Docker Compose
    url: http://prometheus:9090
    # Definindo um UID legível e imutável
    uid: prometheus-homelab
    isDefault: true
    editable: false
