# --- Armazenamento ---
data-dir=/opt/blockchain/monero
log-file=/opt/blockchain/monero/bitmonero.log
log-level=0

# --- Rede e Tor (Fase 4: Darknet) ---
# Força a comunicação P2P exclusivamente pela rede Tor local
proxy=127.0.0.1:9050
# Isola a transmissão de transações (Broadcast) em circuitos Tor separados para evitar correlação de IP (Dandelion++)
tx-proxy=tor,127.0.0.1:9050,10

# Limites de conexão para estabilidade do Tor
out-peers=16
in-peers=0
no-igd=1

# --- RPC (A Ponte para a Feather Wallet) ---
rpc-bind-ip=0.0.0.0
rpc-bind-port=18081
restricted-rpc=1
confirm-external-bind=1
