{
 "title": "cAdvisor exporter",
 "tags": [
  "cadvisor",
  "docker"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{image!=\"\", instance=~\"$host\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Containers Killed Due to Out of Memory (24h)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(container_oom_events_total{image!=\"\", instance=~\"$host\", name=~\"$container\", name=~\".+\"}[24h])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write Rate (I/O)",
   "type": "timeseries",
   "gridPos": { "x": 4, "y": 0, "w": 10, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_fs_writes_bytes_total{image!=\"\", instance=~\"$host\", name=~\"$container\", name=~\".+\"}[2m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Read Rate (I/O)",
   "type": "timeseries",
   "gridPos": { "x": 14, "y": 0, "w": 10, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_fs_reads_bytes_total{image!=\"\", instance=~\"$host\", name=~\"$container\", name=~\".+\"}[2m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", instance=~\"$host\",name=~\"$container\",name=~\".+\"}[5m])) by (name) / scalar(max(machine_cpu_cores{instance=~\"$host\"})) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", instance=~\"$host\",name=~\"$container\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface=~\"eth0|tailscale0\", image!=\"\", instance=~\"$host\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{interface=~\"eth0|tailscale0\", image!=\"\", instance=~\"$host\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Throttling (CFS Restraints)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_cfs_throttled_seconds_total{image!=\"\", instance=~\"$host\", name=~\"$container\", name=~\".+\"}[5m])) or (sum by(name) (container_memory_working_set_bytes{image!=\"\", instance=~\"$host\", name=~\"$container\", name=~\".+\"}) * 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Saturation (% of Limit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum by(name) (container_memory_working_set_bytes{image!=\"\", instance=~\"$host\", name=~\"$container\", name=~\".+\"}) / (sum by(name) (container_spec_memory_limit_bytes{image!=\"\", instance=~\"$host\", name=~\"$container\", name=~\".+\"}) > 0 and sum by(name) (container_spec_memory_limit_bytes{image!=\"\", instance=~\"$host\", name=~\"$container\", name=~\".+\"}) < 1000000000000)) * 100) or ((sum by(name) (container_memory_working_set_bytes{image!=\"\", instance=~\"$host\", name=~\"$container\", name=~\".+\"}) / scalar(max(machine_memory_bytes{instance=~\"$host\"}))) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{image!=\"\", instance=~\"$host\",name=~\"$container\",name=~\".+\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}