{
 "title": "Crowdsec security engines overview",
 "description": "Overview of your crowdsec security engines",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(cs_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Crowdsec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(cs_info{instance=~\"$instance\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "Decisions Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(cs_active_decisions{instance=~\"$instance\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "Alerts Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(cs_alerts{instance=~\"$instance\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "Parsers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_total{instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Acquisitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(cs_filesource_hits_total{instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(cs_journalctlsource_hits_total{instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(cs_cloudwatch_stream_hits_total{instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(cs_syslogsource_hits_total{instance=~\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Decisions by scenario",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(cs_active_decisions{instance=~\"$instance\"}) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Decisions By Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(cs_active_decisions{instance=~\"$instance\"}) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  { "title": "Parsers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Parsers ok",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(cs_node_hits_ok_total{instance=~\"$instance\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Parsers nok",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "(sum(increase(cs_node_hits_ko_total{instance=~\"$instance\"}[$__rate_interval])) by (source)) or (sum(up{instance=~\"$instance\"}) * 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Buckets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Buckets created",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "(sum(increase(cs_bucket_created_total{instance=~\"$instance\"}[$__rate_interval])) by (name)) or (sum(up{instance=~\"$instance\"}) * 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Buckets overflow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "(sum(increase(cs_bucket_overflowed_total{instance=~\"$instance\"}[$__rate_interval])) by (name)) or (sum(up{instance=~\"$instance\"}) * 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Buckets Timeline",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "(sum(cs_buckets{instance=~\"$instance\"}) by (name)) or (sum(up{instance=~\"$instance\"}) * 0)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}