# Diretório de dados no disco SATA em Passthrough (Samsung 870 EVO 2TB)
datadir=/opt/blockchain/bitcoin

# --- Rede e RPC ---
# Interface de servidor (RPC) e modo de rede
server=1
daemon=0 # O systemd cuidará disso
listen=0 # listen=0 (parasita temporário) impede que o nó sirva blocos históricos a terceiros, durante o IBD, preservando 100% de I/O e CPU para a própria validação.

# --- Segurança (Nó Cego) ---
# Desativa a carteira (Obrigatório para segurança). Chaves residem offline (Tails OS) e no client watch-only (Sparrow/Arch).
disablewallet=1

# --- Otimização de Performance (IBD) ---
# Baixa apenas os blocos consolidados. Ignora a mempool (transações soltas na RAM).
blocksonly=1
# Limite rígido de sockets para não derrubar a bridge virtio de rede.
maxconnections=40
# Aloca 11GB da RAM da VM exclusivamente para o LevelDB. Impede o 'thrashing' (leitura/escrita simultânea) no SSD SATA.
dbcache=11000

# RPC Auth (Acesso do Electrs ou scripts futuros)
# rpcuser=... (Deixaremos comentado por enquanto, pois o Electrs vem depois)
