# Diretório de dados no disco SATA em Passthrough (Samsung 870 EVO 2TB)
datadir=/opt/blockchain/bitcoin

# --- Rede e RPC ---
server=1
daemon=0

# --- Privacidade e Tor ---
# Força todo o tráfego pelo proxy SOCKS5 local do Tor.
proxy=127.0.0.1:9050
onlynet=onion

# PERMITE INBOUND: O nó agora atende pedidos da rede
listen=1
listenonion=1
# Habilita a descoberta automática do Hidden Service via Tor API
discover=1
# Restringe o bind ao localhost para segurança interna
bind=127.0.0.1

# --- Segurança (Nó Cego) ---
disablewallet=1

# --- Otimização de Performance (Produção) ---
blocksonly=1
maxconnections=40
dbcache=512
