# Diretório de dados no disco SATA em Passthrough (Samsung 870 EVO 2TB)
datadir=/opt/blockchain/bitcoin

# --- Rede e RPC ---
server=1
daemon=0

# --- Privacidade e Tor ---
# Força todo o tráfego pelo proxy SOCKS5 local do Tor.
proxy=127.0.0.1:9050
onlynet=onion
# Desativar o listen temporariamente para não complexificar a criação de Hidden Services no Tor agora. O foco é alimentar o Electrs.
listen=0

# --- Segurança (Nó Cego) ---
disablewallet=1

# --- Otimização de Performance (Produção) ---
blocksonly=1
maxconnections=40
# Cache reduzido ao limite operacional para ceder espaço vital ao Electrs e Monero.
dbcache=512

# RPC Auth
# Zero config. O Electrs usará o arquivo .cookie nativo do diretório de dados.
